window._ = require('lodash');
window.$ = window.jQuery = require('../../public/vendor/jquery/jquery.min');
require('bootstrap');
window.Swal = require('../../public/vendor/sweetalert2/sweetalert2.all.js');
window.toastr = require('../../public/vendor/toastr/toastr.min.js');
window.moment = require('moment');
// window.datepicker = require('../../public/bootstrap-datepicker-1.9.0-dist/js/bootstrap-datepicker');
// require('../../public/bootstrap-datepicker-1.9.0-dist/locales');
window.bsCustomFileInput = require('../../public/vendor/bs-custom-file-input/bs-custom-file-input.min');
// window.Popper = require('popper');
// require('../../public/coreui/vendors/@coreui/coreui/js/coreui.bundle.min.js');
// require('../../public/coreui/vendors/simplebar/js/simplebar.min.js');
// import '../../public/coreui/vendors/chart.js/js/chart.min.js';
// require ('../../public/coreui/vendors/@coreui/chartjs/js/coreui-chartjs.js');
// import '../../public/coreui/vendors/@coreui/utils/js/coreui-utils.js';
