import _ from 'lodash';
window._ = _;
import 'bootstrap';
import Popper from '../../public/vendor/popper/popper';
window.Popper = Popper;
window.$ = window.jQuery = require('jquery');
import Swal from '../../public/vendor/sweetalert2/sweetalert2.all.js';
window.Swal = Swal;
import moment from 'moment';
window.moment = moment;
import coreui from '../../public/coreui/vendors/@coreui/coreui/js/coreui.bundle.min.js';
window.coreui = coreui;
import '../../public/coreui/vendors/simplebar/js/simplebar.min.js';
// require('../../vendor/bastinald/laravel-livewire-modals/resources/js/modals');
import '@selectize/selectize';
import '../../public/coreui/js/toasts.js';